name: Sigslot Unit Tests

on:
  push:
    branches:
      - master
      - main
      - ci
      - perf

  pull_request:
    branches:
      - master
      - main

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: ['Debug', 'Release']
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Configure sigslot
        run: |
          cmake -E make_directory build
          cmake                                              \
            -DCMAKE_BUILD_TYPE="${{ matrix.build_type }}"    \
            -DSIGSLOT_ENABLE_MANY_WARNINGS=ON                \
            -DSIGSLOT_COMPILE_TESTS=ON                       \
            -DSIGSLOT_COMPILE_EXAMPLES=ON                    \
            -B build -S .
        shell: bash
      - name: Build Sigslot Examples
        run: cmake --build build --target sigslot-examples --config "${{ matrix.build_type }}"
      - name: Build & Run Sigslot Tests
        run: cmake --build build --target sigslot-tests --config "${{ matrix.build_type }}"
  Sanitizer:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sanitizer: ['SANITIZE_ADDRESS', 'SANITIZE_THREADS', 'SANITIZE_UNDEFINED']
    steps:
      - uses: actions/checkout@v3
      - name: Configure sigslot
        run: |
          cmake -E make_directory build
          cmake                                              \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo                \
            -DSIGSLOT_ENABLE_MANY_WARNINGS=ON                \
            -DSIGSLOT_ENABLE_PROFILING=ON                    \
            -DSIGSLOT_${{ matrix.sanitizer }}=ON             \
            -DSIGSLOT_COMPILE_TESTS=ON                       \
            -DSIGSLOT_COMPILE_EXAMPLES=ON                    \
            -B build -S .
        shell: bash
      - name: Build Sigslot Examples
        run: cmake --build build --target sigslot-examples --config RelWithDebInfo
      - name: Build & Run Sigslot Tests
        run: cmake --build build --target sigslot-tests --config RelWithDebInfo
